/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Mark {
  'studentId' : string,
  'score' : number,
  'subjectId' : string,
  'examType' : string,
}
export interface Student {
  'contact' : string,
  'studentId' : string,
  'name' : string,
  'className' : string,
}
export interface Subject { 'name' : string, 'subjectId' : string }
export type UserRole = { 'admin' : null } |
  { 'faculty' : null } |
  { 'student' : null };
export interface _SERVICE {
  'addMark' : ActorMethod<[string, string, number, string], undefined>,
  'addStudent' : ActorMethod<[string, string, string, string], undefined>,
  'addSubject' : ActorMethod<[string, string], undefined>,
  'addUser' : ActorMethod<[string, string, UserRole], undefined>,
  'getStudentMarks' : ActorMethod<[string], Array<Mark>>,
  'getTotalStudents' : ActorMethod<[], bigint>,
  'listStudents' : ActorMethod<[], Array<Student>>,
  'listSubjects' : ActorMethod<[], Array<Subject>>,
  'login' : ActorMethod<[string, string], UserRole>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];