/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'faculty' : IDL.Null,
  'student' : IDL.Null,
});
export const Mark = IDL.Record({
  'studentId' : IDL.Text,
  'score' : IDL.Float64,
  'subjectId' : IDL.Text,
  'examType' : IDL.Text,
});
export const Student = IDL.Record({
  'contact' : IDL.Text,
  'studentId' : IDL.Text,
  'name' : IDL.Text,
  'className' : IDL.Text,
});
export const Subject = IDL.Record({
  'name' : IDL.Text,
  'subjectId' : IDL.Text,
});

export const idlService = IDL.Service({
  'addMark' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64, IDL.Text], [], []),
  'addStudent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addSubject' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addUser' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
  'getStudentMarks' : IDL.Func([IDL.Text], [IDL.Vec(Mark)], ['query']),
  'getTotalStudents' : IDL.Func([], [IDL.Nat], ['query']),
  'listStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'listSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [UserRole], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'faculty' : IDL.Null,
    'student' : IDL.Null,
  });
  const Mark = IDL.Record({
    'studentId' : IDL.Text,
    'score' : IDL.Float64,
    'subjectId' : IDL.Text,
    'examType' : IDL.Text,
  });
  const Student = IDL.Record({
    'contact' : IDL.Text,
    'studentId' : IDL.Text,
    'name' : IDL.Text,
    'className' : IDL.Text,
  });
  const Subject = IDL.Record({ 'name' : IDL.Text, 'subjectId' : IDL.Text });
  
  return IDL.Service({
    'addMark' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64, IDL.Text], [], []),
    'addStudent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'addSubject' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addUser' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
    'getStudentMarks' : IDL.Func([IDL.Text], [IDL.Vec(Mark)], ['query']),
    'getTotalStudents' : IDL.Func([], [IDL.Nat], ['query']),
    'listStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'listSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [UserRole], []),
  });
};

export const init = ({ IDL }) => { return []; };